wsgi/myproject/todo/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^', include('todoapp.urls')),
    url(r'^admin/', admin.site.urls),
]

wsgi/myproject/todoapp/urls.py
from django.conf.urls import url

from . import views

app_name='todo'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^clear/', views.clear, name='clear'),
    url(r'^edit/(?P<task_id>[0-9]+)', views.edit, name='edit'),
    url(r'^completed/(?P<task_id>[0-9]+)', views.completed, name='completed'),
    url(r'^delete/(?P<task_id>[0-9]+)', views.delete, name='delete'),    
    url(r'^bookmark/(?P<task_id>[0-9]+)', views.bookmark, name='bookmark'),
    url(r'^search/', views.search, name='search'),
]

wsgi/myproject/todoapp/models.py
from __future__ import unicode_literals
from django.db import models

# Create your models here.
class Task(models.Model):
    task_text = models.CharField(max_length=200)
    tag_text = models.CharField(max_length=200, default="NULL")
    entry_date = models.DateTimeField('date entered')
    done = models.BooleanField(default=False)
    bookmarked = models.BooleanField(default=False)
    def __str__(self):
        desc = "Task - " + self.task_text + ".\nTags - " + self.tag_text + ".\n"
        return desc

wsgi/myproject/todoapp/forms.py
from django import forms

class TaskForm(forms.Form):
    enter_task = forms.CharField(label='Task', max_length=200, widget=forms.TextInput(attrs={'placeholder': 'Enter the Task', 'size':'55'}))
    enter_tags = forms.CharField(label='Tags', max_length=50, widget=forms.TextInput(attrs={'placeholder': 'Enter Tags separated by space', 'size':'55'}))
    bookmark = forms.BooleanField(initial=False, required=False)

class EditForm(forms.Form):
    enter_task = forms.CharField(label='Task', max_length=200, required=False, widget=forms.TextInput(attrs={'placeholder': 'Enter Task | Leave blank to not modify', 'size':'55'}))
    enter_tags = forms.CharField(label='Tags', max_length=50, required=False, widget=forms.TextInput(attrs={'placeholder': 'Tags | Leave blank to not modify', 'size':'55'}))

class SearchTask(forms.Form):
    search_task = forms.CharField(label='Enter Tags', max_length=200, required=False, widget=forms.TextInput(attrs={'placeholder': 'Enter the Tag/s', 'size':'45'}))

wsgi/myproject/todoapp/views.py
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponse, HttpResponseRedirect
from django.utils import timezone
from .models import Task
from .forms import TaskForm, EditForm, SearchTask
import re

def processText(uStr):
    x = re.findall(r"[\w']+", uStr.encode('ascii', 'ignore'))
    x = list(set([item.strip().lower() for item in x]))
    text = filter(None, x)
    text = ', '.join(text)
    return text

def doesItExist(task_id):
    try:
        task = get_object_or_404(Task, pk=task_id)
    except :
        return 'no'

def index(request):
    if request.method == 'POST':
        form = TaskForm(request.POST)
        if form.is_valid():
            task = Task(task_text=form.cleaned_data['enter_task'], tag_text=processText(form.cleaned_data['enter_tags']), entry_date=timezone.now(), bookmarked=form.cleaned_data['bookmark'])
            task.save()
            return HttpResponseRedirect('/')
    else:
        form = TaskForm()
    task_list = Task.objects.order_by('entry_date')
    bk_list = Task.objects.filter(bookmarked=True)
    return render(request, 'index.html', {
        'form': form,
        'task_list': task_list,
        'bk_list':bk_list
    })

def clear(request):
    Task.objects.all().delete()
    return HttpResponseRedirect('/')

def edit(request, task_id):
    if doesItExist(task_id)=='no':
        return HttpResponse("<center><h1><b>Error - 404</b></h1><br /><h3>Page Does not exist.</h3><br /> <a href=""/""> Go Back </a></center>")
    task = get_object_or_404(Task, pk=task_id)
    if request.method == 'POST':
        form = EditForm(request.POST)
        if form.is_valid():
            if form.cleaned_data['enter_task'] != '':
                task.task_text = form.cleaned_data['enter_task']
            if form.cleaned_data['enter_tags'] != '':
                task.tag_text = processText(form.cleaned_data['enter_tags'])
            task.save()
            return HttpResponseRedirect('/')
    else:
        form = EditForm()
    return render(request, 'edit.html', {'form':form, 'task':task})

def completed(request, task_id):
    if doesItExist(task_id)=='no':
        return HttpResponse("<center><h1><b>Error - 404</b></h1><br /><h3>Page Does not exist.</h3><br /> <a href=""/""> Go Back </a></center>")
    task = get_object_or_404(Task, pk=task_id)
    if task.done==True:
        task.done=False
    else:
        task.done=True
    task.save()
    return HttpResponseRedirect('/')

def bookmark(request, task_id):
    if doesItExist(task_id)=='no':
        return HttpResponse("<center><h1><b>Error - 404</b></h1><br /><h3>Page Does not exist.</h3><br /> <a href=""/""> Go Back </a></center>")
    task = get_object_or_404(Task, pk=task_id)
    if task.bookmarked==True:
        task.bookmarked=False
    else:
        task.bookmarked=True
    task.save()
    return HttpResponseRedirect('/')

def delete(request, task_id):
    task = get_object_or_404(Task, pk=task_id)
    task.delete()
    return HttpResponseRedirect('/')

def search(request):
    all_tags = {}
    tags = Task.objects.all()
    for i in range(Task.objects.all().count()):
        all_tags[tags[i].id] = tags[i].tag_text.encode('ascii', 'ignore').split(", ")
    full_list = list(set([item.strip() for sublist in all_tags.values() for item in sublist]))
    if request.method == "POST":
        form = SearchTask(request.POST)
        if form.is_valid():
            resultFound = []
            key = re.findall(r"[\w']+", form.cleaned_data['search_task'].encode('ascii', 'ignore'))
            key = list(set([item.strip().lower() for item in key]))
            for i in key:
                for j in all_tags.keys():
                    if i in all_tags[j]:
                        resultFound.append(j)
            result = Task.objects.filter(id__in=resultFound)
            return render(request, 'search.html', {'form': form, 'alltags':full_list, 'resultFound':result, 'method':"POST"})
    else:
        form = SearchTask()
    return render(request, 'search.html', {'form': form, 'alltags':full_list, 'method':"GET"})

wsgi/myproject/todoapp/templates/edit.html
{% extends "layout.html" %}
{% block content%}

<div style="margin:20px auto; width:85%;">
  <h1 class="text-center text-primary"> You are Editing</h1><br>
  <table class="table-responsive" style="width:80%;margin:0 auto;">
    <tbody>
      <tr style="border-bottom:2px solid darkblue;">
        <th style="border-right:3px solid darkblue;width:20%"> Task </th>
        <td> {{task.task_text}} </td>
      </tr>
      <tr>
        <th style="border-right:3px solid darkblue; width:20%"> Tags </th>
      <td> {{task.tag_text}} </td>
      </tr>
    </tbody>
    </table>
    <p style="margin:20px auto; width:60%; text-align:center;">
      You can modify above set here -
      Leave the field blank if it's not to be changed
    </p>
    <form style="width: 100%; padding: 1em 2em 0; display:inherit;" action="/edit/{{task.id}}" method="post">
        {% csrf_token %}
        {{form.enter_task}}
        {{form.enter_tags}}
        <center> <input type="submit" class="btn btn-default" value="Submit" /> </center>
    </form>
    <br />
    <p style="font-size:115%; text-align:center; margin:10px auto;"><a href="/">Go Back</a></p>
</div>
{% endblock content%}

wsgi/myproject/todoapp/templates/index.html
{% extends "layout.html" %}
{% block content %}
<body>
  <!DOCTYPE html>
<html>
<head>
<title>Facebook Login JavaScript Example</title>
<meta charset="UTF-8">
</head>
<body>
<script>
  // This is called with the results from from FB.getLoginStatus().
  function statusChangeCallback(response) {
    console.log('statusChangeCallback');
    console.log(response);
    // The response object is returned with a status field that lets the
    // app know the current login status of the person.
    // Full docs on the response object can be found in the documentation
    // for FB.getLoginStatus().
    if (response.status === 'connected') {
      // Logged into your app and Facebook.
      testAPI();
    } else if (response.status === 'not_authorized') {
      // The person is logged into Facebook, but not your app.
      document.getElementById('status').innerHTML = 'Please log ' +
        'into this app.';
    } else {
      // The person is not logged into Facebook, so we're not sure if
      // they are logged into this app or not.
      document.getElementById('status').innerHTML = 'Please log ' +
        'into Facebook.';
    }
  }

  // This function is called when someone finishes with the Login
  // Button.  See the onlogin handler attached to it in the sample
  // code below.
  function checkLoginState() {
    FB.getLoginStatus(function(response) {
      statusChangeCallback(response);
    });
  }

  window.fbAsyncInit = function() {
  FB.init({
    appId      : '{your-app-id}',
    cookie     : true,  // enable cookies to allow the server to access
                        // the session
    xfbml      : true,  // parse social plugins on this page
    version    : 'v2.5' // use graph api version 2.5
  });

  // Now that we've initialized the JavaScript SDK, we call
  // FB.getLoginStatus().  This function gets the state of the
  // person visiting this page and can return one of three states to
  // the callback you provide.  They can be:
  //
  // 1. Logged into your app ('connected')
  // 2. Logged into Facebook, but not your app ('not_authorized')
  // 3. Not logged into Facebook and can't tell if they are logged into
  //    your app or not.
  //
  // These three cases are handled in the callback function.

  FB.getLoginStatus(function(response) {
    statusChangeCallback(response);
  });

  };

  // Load the SDK asynchronously
  (function(d, s, id) {
    var js, fjs = d.getElementsByTagName(s)[0];
    if (d.getElementById(id)) return;
    js = d.createElement(s); js.id = id;
    js.src = "//connect.facebook.net/en_US/sdk.js";
    fjs.parentNode.insertBefore(js, fjs);
  }(document, 'script', 'facebook-jssdk'));

  // Here we run a very simple test of the Graph API after login is
  // successful.  See statusChangeCallback() for when this call is made.
  function testAPI() {
    console.log('Welcome!  Fetching your information.... ');
    FB.api('/me', function(response) {
      console.log('Successful login for: ' + response.name);
      document.getElementById('status').innerHTML =
        'Thanks for logging in, ' + response.name + '!';
    });
  }
</script>

<!--
  Below we include the Login Button social plugin. This button uses
  the JavaScript SDK to present a graphical Login button that triggers
  the FB.login() function when clicked.
-->

<fb:login-button scope="public_profile,email" onlogin="checkLoginState();">
</fb:login-button>

<div id="status">
</div>
    <div class="section">
      <div class="container-fluid">
        <div class="row">
          <div class="col-md-8" style="z-index:3;">
            <h1 class="text-center text-primary"> <i class="fa fa-fw fa-tasks text-primary"></i>WhatTodo?</h1>
              <form class="forms" action="/" method="post">
                {% csrf_token %}
                {{form.enter_task}}
                {{form.enter_tags}}
                <center><b style="padding:10px"> {{form.bookmark}} Bookmark </b>
                   <input type="submit" class="btn btn-default" value="Submit" /> </center>
              </form>
              <br/>
              <div class="col-md-12" id="tasks">
                <hr> <p style="margin:5px"> <a href="{% url 'todo:search' %}"style="font-size:150%"><i class="fa fa-fw fa-search"></i> <b> Search Tasks by Tags </b></a></p> <hr>
                <br>
                  {% if task_list %}
                  <table class="table-responsive">
                  <thead style="border-bottom:2px solid darkblue;"> <tr><th>#</th> <th>Task &amp; Tags</th> <th colspan="4"> Options </th></tr></thead>
                  <tbody>
                    {% for task in task_list %}
                    <tr style="border-bottom:2px solid steelblue">
                      <td style="vertical-align:middle;"> {{forloop.counter}} </td>
                      <td style="width:80%; padding:20px;"> {{task.task_text}} <hr style="border-color:grey; width:50%; margin:auto;"> {{task.tag_text}} </td>
                      <th style="padding:5px;"><a href="{% url 'todo:edit' task.id %}" >&#x270E; </a></th>
                      <th style="padding:5px;">
                        {% if task.done %}
                        <a href="{% url 'todo:completed' task.id%}" title="Completed">&#x2714;</a>
                        {% else %}
                        <a href="{% url 'todo:completed' task.id%}" title="Not Completed"> &#x2705; </a>
                        {% endif %}
                      </th>
                      <th style="padding:5px;">
                        {% if task.bookmarked %}
                        <a href="{% url 'todo:bookmark' task.id%}"> &#x2605; </a>
                        {%else%}
                        <a href="{% url 'todo:bookmark' task.id%}"> &#x2606; </a>
                        {% endif %}
                      </th>
                      <th style="padding:5px;"> <a href="{% url 'todo:delete' task.id%}"> &#x2620; </a> </th>
                    </tr>
                    {% endfor %}
                  </tbody>
                </table>
                {% else %}
                  <p style="font-size:150%; padding-top:5px; text-align:center;">No tasks available.</p>
                  <div class="col-md-offset-3 col-md-6 col-md-offset-3" style="margin-bottom:20px;opacity:0.65; filter:alpha(opacity=65)">
                      <ul class="list-unstyled">
                        <li>
                          <b>'WhatToDo?' is a simple task management app</b>
                        </li>
                        <li>Edit your tasks/Tags</li>
                        <li>Bookmark specfic tasks for easy access</li>
                        <li>Search Tasks by its Tags</li>
                      </ul>
                  </div>
                  {% endif %}
          </div>
        </div>
          <div class="col-md-4" id="bookmarks">
            <h1 class="text-center text-primary"> &#x2605; Bookmarked Tasks </h1><br/ >
            <table class="table-responsive">
            {% if bk_list %}
            <thead style="border-bottom:2px solid darkblue;"> <tr><th>#</th> <th>Task &amp; Tags</th> <th>? </th></tr></thead>
              <tbody>
              {% for task in bk_list %}
                <tr style="border-bottom:2px solid steelblue;">
                  <td style="vertical-align:middle;"> {{ forloop.counter }}  </td>
                  <td> {{task.task_text}} <hr style="border-width:2px; border-color:grey;width:50%;margin:auto;"> {{task.tag_text}} </td>
                  <th> <a href="{%url 'todo:bookmark' task.id%}"> &#x2605; </a> </th>
                </tr>
              {% endfor %}
              </tbody>
              </table>
            {% else %}
              <p style="font-size:150%; text-align:center;">No tasks bookmarked.</p>
            {% endif %}
            <div style="margin:30px auto; width:90%;" align="center">
              <a href="https://gitlab.com/manjuhere/todoapp" target="_blank"><i class="fa fa-fw fa-github"></i></a>
              <a href="https://angel.co/manjunath-chandrashekar" target="_blank"><i class="fa -official fa-fw fa-angellist"></i></a>
              <a href="https://www.linkedin.com/in/manjunathchandrashekar" target="_blank"><i class="fa fa-fw hub fa-linkedin-square"></i></a>
            </div>
          </div>
        </div>
      </div>
    </div>
{% endblock %}

wsgi/myproject/todoapp/templates/layout.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-16">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <script type="text/javascript" src="http://cdnjs.cloudflare.com/ajax/libs/jquery/2.0.3/jquery.min.js"></script>
    <script type="text/javascript" src="http://netdna.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js"></script>
    <link href="http://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.3.0/css/font-awesome.min.css" rel="stylesheet" type="text/css">
    <link href="http://pingendo.github.io/pingendo-bootstrap/themes/default/bootstrap.css" rel="stylesheet" type="text/css">
    <title>{% block title %}WhatTodo{% endblock %}</title>
  </head>
  <style media="screen">
    html,body {background-color: lightsteelblue; height:100%;}
    a {text-decoration: none;font-size: 200%}
    th, td { vertical-align:middle; text-align: center;}
    td {padding-top: 10px; padding-bottom: 10px;}
    input[type=text] {
      padding: 6px 10px;
      margin: 5px 0;
      box-sizing: border-box;
      width: 100%; padding: .5em 1em;
    }
    input[type=text]:focus {
      border: 3px solid #555;
    }
    hr {border-color: black; border-width: 3px; margin:auto; width: 50%}
    input[type=submit] {
      display: inline;
      border: none;
      cursor: pointer;
      color: black; padding: .5em 2em; white-space: nowrap; margin: 0 0 0 0em;
    }
    .table-responsive {
      width: 100%;
      overflow-x: auto;
      -webkit-overflow-scrolling: touch;
      -ms-overflow-style: -ms-autohiding-scrollbar;
      border-collapse: collapse;
      border: 0;
    }
    th:hover {
      background-color:lightslategray;
    }
    .section {
      padding: 0px;
    }
    .forms {
      width: 100%; padding: 1em 2em 0;
      display: table-cell;
    }
    .list-unstyled {
      padding: 5px;
      font-size: 110%;
      text-align: left;
    }
    #bookmarks{
      position: fixed;
      right: 0%;
      height: 100%;
      overflow-y: auto;
      z-index: 2;
    }
    @media screen and (max-width: 992px) {
      #bookmarks {
        position: absolute;
        overflow: auto;
        left: 0;
        right: 0;
      }
    }
    #tasks  {
      text-align: center;
      width: 100%;
    }
    #highlighttags  {
      width: 60%;
      margin: 0 auto;
      background-color: lightblue;
      align-self: center;
    }
    #highlighttags span {
	    background:#fff;
	    padding:1px 2px;
      margin: 15px 5px;
	    color:#bb610b;
	    size:200%
    }
  </style>
<body>
{% block content%}
{% endblock content%}
</body>

wsgi/myproject/todoapp/templates/search.html
{% extends "layout.html" %}
{% block title %}Todo-Search{% endblock title%}
{% block content %}

<div>
  <h1 class="text-center text-primary"> <i class="fa fa-fw fa-search"></i>Search By Tags</h1><br>
  <div id="highlighttags">

    <p style="font-size:150%; text-align:center;">All Tags</p>
    <div style="margin:0 auto; width:80%; ">
      {% for t in alltags%}
      <span>{{t}}</span>
      {% endfor %}
    </div>
  </div>
  <div style="margin:0 auto;width:80%;">
  <br />
  <form style=";width: 100%; padding: 1em 2em 0; display:inherit;" action="/search/{{text}}" method="post">
    {% csrf_token %}
      {{ form.search_task }} <center><input type="submit" value="Search"></center>
  </form>
  <br /><hr><br />
  </div>
</div>
<div style="margin:20px auto; width:80%;">
  {% if method == "POST" %}
  <table class="table-responsive">
  {% if resultFound %}
  <thead style="border-bottom:2px solid darkblue;"> <tr><th>#</th> <th>Task &amp; Tags</th> <th>? </th></tr></thead>
    <tbody>
    {% for task in resultFound %}
      <tr style="border-bottom:2px solid steelblue;">
        <td style="vertical-align:middle;"> {{ forloop.counter }}  </td>
        <td> {{task.task_text}} <hr style="border-width:2px; border-color:grey;width:50%;margin:auto;"> {{task.tag_text}} </td>
        <td> <a href="{%url 'todo:bookmark' task.id%}"> &#x2605; </a> </td>
      </tr>
    {% endfor %}
    </tbody>
    </table>
  {% else %}
      <p style="font-size:300%; text-align:center; margin:100px;"> No Results found :(</p>
  {% endif %}
  {% endif %}
  <p style="font-size:115%; text-align:center; margin:10px auto;"><a href="/">Go Back</a></p>

</div>
{% endblock content %}